Overhaul for 2.6+ robustness
- Build with both the old digest codebase (relying on SHA1_Init and
  friends) and Zeek's new one (using EVP_MD_CTX_new). To do this we
  directly check Zeek's digest.h for the available code. Ideally we'd
  run a compilation test, but this is straightforward enough.

- Refreshed the package/plugin layout from a new init-plugin run. This
  seemed more robust than the undocumented init-plugin -u, which
  apparently wouldn't update the configure script.

- There's some ugliness around configure / configure.pluin -- ideally
  the former would also anticipate simply running some code in the
  latter, so I couldn't quite do what I needed without touching it.

- For the record, the init-plugin command used was:

  $ init-plugin bro-community-id Corelight CommunityID

  Seems important to keep this around so one can potentially run the
  -u version with the same arguments at a later time.

diff --git a/tests/Scripts/get-bro-env b/tests/Scripts/get-bro-env
--- a/tests/Scripts/get-bro-env
+++ b/tests/Scripts/get-bro-env
@@ -2,20 +2,35 @@
 #
 # BTest helper for getting values for Bro-related environment variables.
 
-base=$(dirname $0)
-bro=$(bro-pkg config bro_dist)
+base=`dirname $0`
+bro_dist=`cat ${base}/../../build/CMakeCache.txt 2>/dev/null | grep BRO_DIST | cut -d = -f 2`
 
-if [ "$1" = "brobase" ]; then
-    echo ${bro}
-elif [ "$1" = "bropath" ]; then
-    ${bro}/build/bro-path-dev
-elif [ "$1" = "bro_plugin_path" ]; then
-    ( cd ${base}/../.. && pwd )
-elif [ "$1" = "bro_seed_file" ]; then
-    echo ${bro}/testing/btest/random.seed
-elif [ "$1" = "path" ]; then
-    echo ${bro}/build/src:${bro}/aux/btest:${base}/:${bro}/aux/bro-cut:$PATH
+if [ -n "${bro_dist}" ]; then
+    if [ "$1" = "bropath" ]; then
+        ${bro_dist}/build/bro-path-dev
+    elif [ "$1" = "bro_plugin_path" ]; then
+        ( cd ${base}/../.. && pwd )
+    elif [ "$1" = "path" ]; then
+        echo ${bro_dist}/build/src:${bro_dist}/aux/btest:${base}/:${bro_dist}/aux/bro-cut:$PATH
+    else
+        echo "usage: `basename $0` <var>" >&2
+        exit 1
+    fi
 else
-    echo "usage: `basename $0` <var>" >&2
-    exit 1
+    # Use Bro installation for testing. In this case bro-config must be in PATH.
+    if ! which bro-config >/dev/null; then
+        echo "bro-config not found" >&2
+        exit 1
+    fi
+
+    if [ "$1" = "bropath" ]; then
+        bro-config --bropath
+    elif [ "$1" = "bro_plugin_path" ]; then
+        ( cd ${base}/../.. && pwd )
+    elif [ "$1" = "path" ]; then
+        echo ${PATH}
+    else
+        echo "usage: `basename $0` <var>" >&2
+        exit 1
+    fi
 fi
